//
//  GlobalConstant.swift
//  CaBoApp
//
//  Created by vadym vasylaki on 11.12.2025.
//

import Foundation

struct GlobalConstant {
    static let cocktailsModels: [CocktailModel] = [
        CocktailModel(title: "Malecón Mojito Night", image: IconEnum.malecónMojitoNight.icon, modeEnum: .deep, dificulty: .easy, ingredients: "White Cuban rum\nLime juice\nFresh mint\nSugar\nSoda\n", origin: "A nighttime variation of the classic mojito, inspired by the lights of the Malecón.", story: "Mojito is the embodiment of Cuban freshness, but at night it becomes magical. The light of the lanterns is reflected in the glass, and mint and lime are refreshing after a hot day. This is a cocktail for those looking for lightness and romance under the stars.", facts: "The Malecón is an iconic meeting place in Havana. Mint and lime are key ingredients in Cuban mixology, especially in summer cocktails."),
        CocktailModel(title: "Cuban Classics: Daiquiri", image: IconEnum.cubanClassicsDaiquiri.icon, modeEnum: .relax, dificulty: .medium, ingredients: "White rum\nLime juice\nSugar", origin: "One of the oldest Cuban cocktails, popularized by Hemingway in the bars of Havana.", story: "Daiquiri is a taste of retro Havana, where the bar is the center of life. Soft light, vintage posters, and a glass filled with history. A cocktail for connoisseurs of classics and the atmosphere of the old town.", facts: "Named after the Daiquiri mine in eastern Cuba. It became popular at the beginning of the 20th century and remains an icon of Cuban bar art."),
        CocktailModel(title: "Cuba Libre Origins", image: IconEnum.cubaLibreOrigins.icon, modeEnum: .party, dificulty: .easy, ingredients: "Cuban rum\nCircles\nLime juice\n", origin: "It was created in honor of the liberation of Cuba from Spanish rule - hence \("Libre").", story: "Cuba Libre is not just a cocktail, but a toast to freedom. Ego drinks in bars with revolutionary posters, to the sounds of old songs. Warm brown and red tones reflect the passion and power of change.", facts: "The name appeared at the beginning of the 20th century, when American soldiers mixed rum with cola and lime. A drink with political overtones and cultural depth."),
        CocktailModel(title: "Island Breeze Cooler", image: IconEnum.islandBreezeCooler.icon, modeEnum: .relax, dificulty: .easy, ingredients: "Light rum\nLime juice\nMint\nCoconut water or soda water", origin: "A modern refreshing cocktail inspired by the beaches of Varadero and the sea breeze.", story: "This cocktail is like a light breeze from the Caribbean Sea. It cools, relaxes and transports to the atmosphere of a tropical vacation. Ideal for daytime relaxation on the beach.", facts: "Cuba is famous for its beaches and maritime climate. Lime and mint are key components of Cuban mixology, especially in summer cocktails."),
        CocktailModel(title: "Caribbean Storm Punch ", image: IconEnum.caribbeanStormPunch.icon, modeEnum: .party, dificulty: .advanced, ingredients: "Dark rum\nPineapple, passion fruit, lime juice\nGrenadine syrup\nA drop of Angostura", origin: "Fruit punch inspired by the storms of the Caribbean Sea and the contrasts of tropical nature.", story: "This cocktail is like a storm: bright, rich, dramatic. Fuchsia and indigo are the colors of passion and depth. It awakens emotions and reminds of the power of nature.", facts: "The Caribbean region is home to many fruits used in punches. Cuban rum gives the drink character and richness.")
        
    ]
    
    static let cultureLessons: [CultureModel] = [
        CultureModel(title: "Rum Basics & Traditions", image: IconEnum.rumBasicsTraditions.icon, modeEnum: .deep, origin: "Rum is the heart of Cuban culture, a drink with a rich history dating back to colonial times.", story: "Each bottle of rum is a story: about sugar cane, about old factories, about family traditions. Cuban posters on the walls are a visual memory of the past.", facts: "Cuba is one of the world leaders in the production of rum. Local brands such as Havana Club have become symbols of national identity."),
        CultureModel(title: "Colonial Romance Tales", image: IconEnum.colonialRomanceTales.icon, modeEnum: .romantic, origin: "The architecture of Havana is a mixture of Spanish colonial aesthetics and tropical sensuality.", story: "Balconies wrapped in flowers, sunset reflected in old facades - all this creates an atmosphere of romance and nostalgia.", facts: "Colonial buildings in Havana date back to the 18th and 19th centuries. Many of them are protected as UNESCO cultural heritage."),
        CultureModel(title: "Havana Home Bar Setup", image: IconEnum.havanaHomeBarSetup.icon, modeEnum: .relax, origin: "Home bars are part of Cuban hospitality, where rum is the main character.", story: "Every house has a corner for rum, a lamp with a soft light and glasses ready for an evening conversation. This is a space of coziness and communication.", facts: "Cubans often create home bars from materials at hand, turning them into real art objects."),
        CultureModel(title: "Tropicana Dream Lights", image: IconEnum.tropicanaDreamLights.icon, modeEnum: .party, origin: "Tropicana is a legendary cabaret, a symbol of Cuban nightlife and show culture.", story: "Since 1939, Tropicana has amazed the audience with bright costumes, live music and dancing. This is the place where night becomes art.", facts: "Tropicana is one of the most famous cabarets in the world, with an open stage under the stars and more than 200 artists."),
        CultureModel(title: "Domino Table Tales", image: IconEnum.dominoTableTales.icon, modeEnum: .deep, origin: "Dominoes are a favorite game of Cubans, especially in outdoor courtyards and on verandas.", story: "Playing dominoes is more than leisure. This is a way of communication, exchange of news, laughter and friendship.", facts: "Domino is part of the Cuban identity. Tournaments are even held in Havana, and gaming tables are an important element of yard culture."),
        CultureModel(title: "Paladar Dinner Vibes", image: IconEnum.paladarDinnerVibes.icon, modeEnum: .romantic, origin: "Paladar is a private restaurant, often located in old houses with a family kitchen.", story: "Dinner in a paladare is an intimate experience: candles, homemade food, conversations. This is a place where traditions meet personal history.", facts: "Paladars appeared in the 1990s as an alternative to state restaurants. Today, they are the center of Cuba's gastronomic culture."),
        CultureModel(title: "Sugarcane & Sea Salt", image: IconEnum.sugarcanesSeaSalt.icon, modeEnum: .deep, origin: "The contrast between sugar cane and sea salt is a metaphor for Cuban nature and taste.", story: "This is a visual and taste image of Cuba: the sweetness of the land and the saltiness of the sea, combined in one frame.", facts: "Cuba is a major producer of cane. Sea salt is mined on the coast, especially in the area of ​​Pinar del Río."),
        CultureModel(title: "Buena Noche Terrace", image: IconEnum.buenaNocheTerrace.icon, modeEnum: .relax, origin: "The evening terrace is a place for contemplation, toasts and silence.", story: "In Cuba, evening is a time to slow down. A terrace with a view of the garden or the sea, rum in a glass, and a light breeze — all this creates an atmosphere of peace.", facts: "Terraces are an important part of Cuban architecture. They are used both for recreation and for communication with neighbors."),
        CultureModel(title: "Rum Library Beginner", image: IconEnum.rumLibraryBeginner.icon, modeEnum: .relax, origin: "A home collection of rum is a way to study culture through taste and history.", story: "Each bottle is like a chapter in a book. The light falling on the glass creates an atmosphere of familiarity and enjoyment.", facts: "Many Cubans collect rum as collectors. Bottles of different years and brands are part of the cultural heritage."),
        CultureModel(title: "Cigar Lounge at Home", image: IconEnum.cigarLoungeatHome.icon, modeEnum: .deep, origin: "A Cuban cigar is a symbol of status, ritual and contemplation. The home lounge is a space for silence and a bite.", story: "A cigar in Cuba is not just tobacco, but a cultural gesture. In the lounge with a leather chair and a glass of aged rum, an atmosphere of maturity, thoughtfulness and respect for tradition is created.", facts: "Cuba is the world leader in the production of premium cigars. Cigar lounges are part of city and home culture, especially among collectors and connoisseurs."),
        CultureModel(title: "Kitchen Fiesta Setup", image: IconEnum.kitchenFiestaSetup.icon, modeEnum: .party, origin: "The kitchen is the heart of the Cuban home, where cooking turns into a holiday.", story: "In Cuba, cooking is a collective act: family, neighbors, music, laughter. Kitchen Fiesta is the aroma of spices, the rhythm of salsa and the joy of sharing a meal.", facts: "Cuban cuisine combines Spanish, African and Caribbean influences. Dishes are often prepared in large portions so that there is enough for everyone - this is an expression of hospitality.")
    ]
    
    static let placesModels: [PlacesModel] = [
        PlacesModel(title: "Malecón Sunset Story", image: IconEnum.malecónSunsetStory.icon, modeEnum: .romantic, origin: "The Malecon is a symbol of the meeting of day and night, a place where the sunset becomes a spectacle.", story: "Every evening on the Malecón is a ritual. People gather to look at the sea, share stories, love. The golden light of the sunset and the turquoise water create magic.", facts: "The Malecón stretches for 8 km along the coast of Havana. This is one of the most photographed places in Cuba."),
        PlacesModel(title: " Street Carnival Vibes", image: IconEnum.streetCarnivalVibes.icon, modeEnum: .party, origin: "Cuban carnivals are a mixture of African, Spanish and Caribbean traditions.", story: "Carnival is a celebration of the body and spirit. The streets are filled with rhythms, flowers, and laughter. This is the moment when the whole city becomes a stage.", facts: "The Havana Carnival has been held since the 19th century. Hundreds of dancers, musicians and artists take part in it."),
        PlacesModel(title: "Vedado Vintage Bars", image: IconEnum.vedadoVintageBars.icon, modeEnum: .deep, origin: "Vedado is an area of ​​modernism and bohemian life, where bars preserve the atmosphere of the 20th century.", story: "A bar in Vedado is a place of meetings, conversations, and jazz. The interior with vintage lamps and cocktails based on old recipes create an atmosphere of intellectual relaxation.", facts: "Vedado is the cultural center of Havana with theaters, cinemas and bars that have preserved the spirit of the 1950s."),
        PlacesModel(title: "Midnight on Obispo Street", image: IconEnum.midnightonObispoStreet.icon, modeEnum: .party, origin: "Obispo is one of the liveliest streets in Havana, especially at night.", story: "At night, Obispo turns into a stream of light, music and movement. Tourists and locals meet here to drink, dance and feel the pulse of the city.", facts: "Obispo Street connects the center of Havana with the embankment. Bars, shops and museums are located here."),
        PlacesModel(title: "Malecón Lovers Bench", image: IconEnum.malecónLoversBench.icon, modeEnum: .romantic, origin: "The Malecon is a place of recognition, meeting and farewell.", story: "A bench by the sea is a symbol of intimacy. Steam in silence, sunset, wind - everything speaks without words. This is a moment that remains in memory.", facts: "Dozens of benches have been installed on the Malecon, each of which has witnessed thousands of love stories."),
        PlacesModel(title: "Havana Rooftop Chill", image: IconEnum.havanaRooftopChill.icon, modeEnum: .relax, origin: "The roofs of Havana are hidden worlds where the city is revealed from a new side.", story: "Dinner on the roof is rest, cocktails, conversations. The soft light, the noise of the city below and the stars overhead create an atmosphere of peace.", facts: "Many bars and cafes in Havana are located on the roofs, offering a panoramic view of the city."),
        PlacesModel(title: "Street Market Stories", image: IconEnum.streetMarketStories.icon, modeEnum: .deep, origin: "Markets are the heart of the Cuban economy and communication.", story: "Everything is boiling in the market: voices, aromas, colors. This is a place where you can feel the rhythm of life, hear stories and try real Cuban products.", facts: "Street markets in Havana offer seasonal fruits, spices and homemade dishes. This is an important element of urban culture."),
        PlacesModel(title: "Street Market Stories", image: IconEnum.streetMarketStories.icon, modeEnum: .relax, origin: "A home kitchen is the center of a Cuban home, a place of warmth and taste.", story: "Pots on the stove, the smell of rice and beans, conversations at the table - all this creates an atmosphere of comfort and belonging.", facts: "Cuban cuisine is based on simple ingredients: rice, beans, chicken, spices. Cooking is a collective process."),
        PlacesModel(title: "Old Chevy City Drive", image: IconEnum.oldChevyCityDrive.icon, modeEnum: .relax, origin: "The old American car is part of the visual code of Havana.", story: "Driving a vintage Chevy is a trip back in time. Pastel houses, open windows, music — all this creates an atmosphere of nostalgia.", facts: "More than 60,000 classic cars have been preserved in Cuba, most of which are American models of the 1950s."),
        PlacesModel(title: "Night Under Havana Stars", image: IconEnum.nightUnderHavanaStars.icon, modeEnum: .romantic, origin: "Night in Havana is a time of silence, feelings and contemplation.", story: "Under the stars, the city becomes second nature: soft, intimate, poetic. This is the moment when you want to whisper and look at the sky.", facts: "Havana is one of the few big cities where you can see the stars thanks to the low level of light pollution."),
        PlacesModel(title: "Plaza Vieja Evening Walk", image: IconEnum.plazaViejaEveningWalk.icon, modeEnum: .deep, origin: "Plaza Vieja is one of the oldest squares in Havana, the center of city life.", story: "In the evening, the square comes alive: lanterns, music, walks. This is the place where history meets the present.", facts: "Plaza Vieja was founded in the 16th century. Today, museums, cafes and art galleries are located here.")
    ]
    
    static let homeSessionsModels: [HomeSessionModel] = [
        HomeSessionModel(title: "Evening Domino Ritual", image: IconEnum.eveningDominoRitual.icon, modeEnum: .deep, dificulty: .medium, timeForSession: .fortyPlus, prepare: "The atmosphere of the evening: dimmed lights, rum, snacks, music with rhythm", mix: "A simple cocktail is Cuba Libre or Daiquiri. Serve fruit, cheese, bread", listen: "Let salsa or bolero play. Laughter, conversations, dominoes - all in the rhythm of friendship", reflect: "Discuss history, share memories, finish the evening with light coffee"),
        HomeSessionModel(title: " Home Bar Havana Style", image: IconEnum.homeBarHavanaStyle.icon, modeEnum: .relax, dificulty: .easy, timeForSession: .twentyFive, prepare: "Decorate the bar: a wooden shelf, vintage bottles, glasses, a lamp", mix: "Choose rum - white, dark or aged. Add ice, lime, mint", listen: "Background music: jazz or bolero. Enjoy the moment alone or together", reflect: "Read about the origin of rum, compare flavors, create your own collection"),
        HomeSessionModel(title: "Café Cubano at the Kitchen Table", image: IconEnum.caféCubanoattheKitchenTable.icon, modeEnum: .relax, dificulty: .easy, timeForSession: .twenty, prepare: "Brew strong Café Cubano with sugar. Put the cup on the sunny table", mix: "Add a piece of bread, cheese or sweets - according to your mood", listen: "Background morning music: acoustic or bolero", reflect: "Read a short story, write down your thoughts, start the day with inspiration"),
        HomeSessionModel(title: "Terrace Candlelight Session", image: IconEnum.terraceCandlelightSession.icon, modeEnum: .romantic, dificulty: .medium, timeForSession: .thortyFive, prepare: "Candles, a blanket, a glass of rum or wine. Soft light and silence", mix: "Light cocktail - Daiquiri or Punch. Snacks: cheese, fruit, bread", listen: "Background music: bolero, jazz, acoustics. You can dance or just look at the stars", reflect: "Read a romantic story, write a letter or just be silent"),
        HomeSessionModel(title: "Rum & Storytelling Night", image: IconEnum.rumsStorytellingNight.icon, modeEnum: .deep, dificulty: .medium, timeForSession: .thortyFive, prepare: "Evening mood: lamps, rum, cozy chairs, books or oral histories", mix: "Aged rum or Punch. Snacks: nuts, cheese, fruit", listen: "Background music: bolero, jazz. Stories sound to the rhythm", reflect: "Discuss legends, share memories, create an atmosphere of trust"),
        HomeSessionModel(title: "Cigar Lounge at Home", image: IconEnum.cigarLoungeatHome.icon, modeEnum: .deep, dificulty: .medium, timeForSession: .twentyFourty, prepare: "Armchair, lamp, cigar, glass of rum. Vintage details: books, posters", mix: "Dark or aged rum. Without snacks - emphasis on taste", listen: "Background music: jazz, bolero. The atmosphere is mature and thoughtful", reflect: "Read about cigars, compare aromas, write down your thoughts"),
        HomeSessionModel(title: "Kitchen Fiesta Setup", image: IconEnum.kitchenFiestaSetup.icon, modeEnum: .party, dificulty: .medium, timeForSession: .fortyPlus, prepare: "Heat the stove, take out the spices, turn on the music. Cook with rhythm", mix: "Prepare arroz con pollo, tostones, yuca. Serve with rum or juice", listen: "Salsa, rumba, reggaeton - the kitchen turns into a dance floor", reflect: "Discuss recipes, share family traditions, write down your favorite dishes"),
        HomeSessionModel(title: "Balcony Sunset Ritual", image: IconEnum.balconySunsetRitual.icon, modeEnum: .romantic, dificulty: .easy, timeForSession: .twentyFourty, prepare: "Plaid, glass, candle. The view of the sunset is the main decoration", mix: "Light cocktail - Mojito or Daiquiri. Fruit or cheese", listen: "Background music: bolero, acoustics. Evening silence and light", reflect: "Read poems, write thoughts, just look at the sky"),
        HomeSessionModel(title: "Buena Noche Home Session", image: IconEnum.buenaNocheHomeSession.icon, modeEnum: .relax, dificulty: .easy, timeForSession: .twentyFourty, prepare: "A lamp, a glass of rum, a blanket. Silence and evening air", mix: "Light Punch or Cuba Libre. Light snacks: cheese, bread, fruit", listen: "Jazz, bolero, acoustics. Music for relaxation", reflect: "Read a short story, look at the stars, end the day peacefully")
    ]
    
    static let journayCollections = [cocktailsModels, cultureLessons, placesModels, homeSessionsModels].compactMap({$0})
}

enum JourneyType: Int, CaseIterable {
    case cocktails = 0
    case culture
    case places
    case homeSessions
}
